add json check test2

diff --git a/.github/workflows/run_dev.yml b/.github/workflows/run_dev.yml
--- a/.github/workflows/run_dev.yml
+++ b/.github/workflows/run_dev.yml
@@ -1,10 +1,5 @@
 name: Run NPX
-# on:
-#   push:
-#     branches:
-#       - dev
 
-# run_pre_dev.yml に依存。それが成功すれば実行される。
 on:
   workflow_run:
     workflows: ["JSON Validation"]
@@ -15,7 +10,24 @@ permissions:
   contents: write
 
 jobs:
+  check-previous-workflow:
+    runs-on: ubuntu-latest
+    outputs:
+      status: ${{ steps.check.outputs.status }}
+    steps:
+      - name: Check if JSON Validation was successful
+        id: check
+        run: |
+          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
+            echo "::set-output name=status::failure"
+            exit 1
+          else
+            echo "::set-output name=status::success"
+          fi
+
   run-npx-and-push:
+    needs: check-previous-workflow
+    if: needs.check-previous-workflow.outputs.status == 'success'
     runs-on: ubuntu-latest
 
     steps:
@@ -37,7 +49,6 @@ jobs:
         if: success()
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
         run: |
           git config user.name 'GitHub Actions'
           git config user.email 'actions@github.com'
