fix cover image validation7

diff --git a/.github/workflows/run_dev.yml b/.github/workflows/run_dev.yml
--- a/.github/workflows/run_dev.yml
+++ b/.github/workflows/run_dev.yml
@@ -99,8 +99,6 @@ jobs:
           # Ensure only allowed file types in blog images directories
           for PATH_PATTERN in 'public/blog/**/images/*' 'posts/blog/**/images/*'; do
             for FILE in $PATH_PATTERN; do
-              echo "Checking file: $FILE"
-
               if [ -f "$FILE" ]; then
                 FILE_EXTENSION="${FILE##*.}"
                 ALLOWED_EXTENSION=false
@@ -125,7 +123,7 @@ jobs:
           for FILE in public/author/*.png; do
             if [ -f "$FILE" ]; then
               FILE_SIZE=$(stat -c%s "$FILE")
-              IMAGE_DIMENSIONS=$(file $FILE | grep -o '[0-9]* x [0-9]*')
+              IMAGE_DIMENSIONS=$(file $FILE | grep -o '[0-9]* x [0-9]*' || echo "0 x 0")
               if [ "$IMAGE_DIMENSIONS" != "200 x 200" ]; then
                 echo "File $FILE has invalid dimensions ($IMAGE_DIMENSIONS). Deleting..."
                 git rm $FILE
@@ -135,33 +133,17 @@ jobs:
           done
 
           # Validate cover image files in specified directories
-          set -euxo pipefail
-          
           for FILE in public/blog/**/images/*_cover.png posts/blog/**/images/*_cover.png; do
-          echo "Checking file cover: $FILE"
-
-          if [ -f "$FILE" ]; then
-            FILE_SIZE=$(stat -c%s "$FILE")
-            echo "File size: $FILE_SIZE"
-            
-            IMAGE_DIMENSIONS=$(file $FILE | grep -o '[0-9]* x [0-9]*')
-            echo "Image dimensions: $IMAGE_DIMENSIONS"
-            
-            if [ "$IMAGE_DIMENSIONS" != "1200 x 630" ]; then
-              echo "File $FILE has invalid dimensions ($IMAGE_DIMENSIONS). Attempting to delete..."
-              
-              if git ls-files --error-unmatch "$FILE" > /dev/null 2>&1; then
-                echo "File is tracked by git. Using 'git rm' to delete..."
-                git rm "$FILE"
-              else
-                echo "File is not tracked by git. Using 'rm' to delete..."
-                rm "$FILE"
+            if [ -f "$FILE" ]; then
+              FILE_SIZE=$(stat -c%s "$FILE")
+              IMAGE_DIMENSIONS=$(file $FILE | grep -o '[0-9]* x [0-9]*')
+              IMAGE_DIMENSIONS=$(file "$FILE" | grep -o '[0-9]* x [0-9]*' || echo "0 x 0")
+              if [ "$IMAGE_DIMENSIONS" != "1200 x 630" ]; then
+                echo "File $FILE has invalid dimensions ($IMAGE_DIMENSIONS). Deleting..."
+                git rm $FILE
+                INVALID_FILES_FOUND=true
               fi
-              
-              echo "File $FILE deleted successfully."
-              INVALID_FILES_FOUND=true
             fi
-          fi
           done
 
           # Validate file size in specified directories
