check github action env

diff --git a/.github/workflows/run_pre_dev.yml b/.github/workflows/run_pre_dev.yml
--- a/.github/workflows/run_pre_dev.yml
+++ b/.github/workflows/run_pre_dev.yml
@@ -52,13 +52,13 @@ jobs:
               exit 0
           fi
           
-          for file in $JSON_FILES_CHANGED; do
-              echo "Validating $file..."
-              if ! cat $file | jq empty; then
-                  echo "Error: Invalid JSON in $file"
-                  exit 1
-              fi
-          done
+          # for file in $JSON_FILES_CHANGED; do
+          #     echo "Validating $file..."
+          #     if ! cat $file | jq empty; then
+          #         echo "Error: Invalid JSON in $file"
+          #         exit 1
+          #     fi
+          # done
           
 
 
